## Wordle Helper 
Use Wordle Helper while you're playing Wordle. For each word that you enter in Wordle: 
1. Enter the word in the box to the right of **Enter A Word ->**;
2. For each letter in that word, click on the color that Wordle returned to you;
3. Repeat the process for as many words as you like, that you already entered into Wordle.

For example, consider the *December 16th, 2022* game.  On that day:
* The answer was the word **probe**
* My first word was **slate**
  * Wordle returned <img src="slate.png">
* My next word was **minor**
  * Wordle returned <img src="minor.png">


## wordle_helper: Show all the word possibilites and their probabilities.

### Usage: 
1. Run all of the notebook cells
2. The last cell uses ipywidgets to display the input screen

In [13]:
from IPython.display import HTML

HTML('''<script>
code_show=true; 
function code_toggle() {
 if (code_show){
 $('div.input').hide();
 } else {
 $('div.input').show();
 }
 code_show = !code_show
} 
$( document ).ready(code_toggle);
</script>
<form action="javascript:code_toggle()"><input type="submit" value="Click here to toggle on/off the raw code."></form>''')

In [2]:
import itertools
import string
import numpy as np
import ipywidgets as widgets
from IPython.display import display,display_html

import tqdm
import pdb

import pandas as pd
# from nltk.corpus import words

In [3]:
USE_LOCAL_CSV=True
if USE_LOCAL_CSV:
    df = pd.read_csv('df_wordl_words.csv')
    df_ugf = pd.read_csv('unigram_freq.csv')
else:
    sheet_url ='https://docs.google.com/spreadsheets/d/1rYkOLXEaSvq5cMY1IfpwTx4RRtIv8GNg-CyoM0Ysc84/edit#gid=2066977162'
    csv_export_url = sheet_url.replace('/edit#gid=', '/export?format=csv&gid=')
    df = pd.read_csv(csv_export_url)
    sheet_url ='https://docs.google.com/spreadsheets/d/1NbUDdW_W4eTSuiRpcwnXB7B2r5JO4A3nbHfPxyIKXcY/edit#gid=1269657289'
    csv_export_url = sheet_url.replace('/edit#gid=', '/export?format=csv&gid=')
    df_ugf = pd.read_csv(csv_export_url)

df_ww = pd.read_csv('wordle_words.csv')
df_ww['word'] = df_ww.index
df_ww.index = range(len(df_ww))

df_ugf = df_ugf[~df_ugf.word.isna()]    
df_ugf.words = df_ugf.word.str.strip(' ')

df_ugf = df_ugf[df_ugf.word.isin(df_ww.word.values)]
c1 = df_ugf.word.str.len()==5
c2 = df_ugf.word.str.slice(0,1).str.lower() == df_ugf.word.str.slice(0,1)
nltk_words = df_ugf[c1 & c2].word.values
# nltk_words = df.word.values
len(nltk_words)

/var/folders/fl/tvtrn4x93cx6s2vpm9b7gn0w0000gn/T/ipykernel_34033/1325886786.py:18: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df_ugf.words = df_ugf.word.str.strip(' ')

2308

In [4]:
def new_condition(word,letter_status):
    good_letters = []
    for i,letter in enumerate(list(word)):
        if letter_status[i]<3:
            good_letters.append(letter)
    def inner_test(w):
        new_conditions = []
        for i,letter in enumerate(list(word)):
            if letter_status[i]==0:
                new_conditions.append(
                    letter in w 
                )                
            elif letter_status[i]==1:
                new_conditions.append(
                    letter in w[i] 
                )                
            elif letter_status[i]==2:
                new_conditions.append(
                    (letter in w) and (letter not in w[i])
                )
            else:
                new_conditions.append(
                    letter not in w
                )
        return new_conditions
    return inner_test,good_letters

class wordl():
    def __init__(self,show_progress=True):
        self.wordlist = []
        self.letter_list = []
        self.letter_status = []
        self.conditions = []
        self.show_progress = show_progress
        all_words = set(
            nltk_words
        )
        self.nltk_words =  set(
            [
                wo 
                for wo in all_words
                if (len(wo)==5) and (wo.lower()==wo)
            ]
        )
    
    def add_word(self,word,letter_status,debug_word=''):
        self.wordlist.append(word)
        self.letter_status.append(letter_status)
        condition_list,letter_list = new_condition(word,letter_status)
        self.conditions.append(condition_list)
        self.letter_list.extend(letter_list)
        self.letter_list = list(set(self.letter_list))
    
    def conds(self,w):
        cond_results = []
        for i in range(len(self.conditions)):
            cond_results.extend(self.conditions[i](w))
        return all(cond_results)
    


    def try_it(self,letter_list=None):
        words = []
        curr_lets = self.letter_list if letter_list is None else letter_list
        poss_words = [
            w for w in self.nltk_words
            if len(set(curr_lets).intersection(w))==len(curr_lets)
        ]
        for w in poss_words:
            if self.conds(w):
                words.append(w)
        return words

In [5]:
%%html
<style>
.mytext {
    text-transform:uppercase;
    font-weight: bold;
    color: blue;
    font-size:100px;
    text-align:center;
}
</style>

In [6]:
perc=100

results_output = widgets.Output(
)

In [7]:
def run_it():    
    results_output.clear_output()
    table_style = {'description_width': 'auto'}
    table_layout = {'width':'auto', 'min_width':'15px',  'min_height':'28px'}

    num_tboxes = 5
    tboxes = [
        widgets.Text(
            layout=table_layout,
    #         layout={'width':'25%'},
            style={'description_width': 'auto'} #table_style
        )
        for i in range(num_tboxes)
    ]  


    letter_status = {}
    dropdowns = []
    button_group_array = []

    def create_on_letter_button_clicked(letter_number,i):
        def on_letter_button_clicked(change):
            change.icon='check'
            letter_status[letter_number] = i
            for j in [k for k in range(3) if k != i]:
                button_group_array[letter_number][j].icon='uncheck'

        return on_letter_button_clicked

    def make_button_group(letter_number):
        button_children = []
        color_index = ["#49BE25","#D5C450","#A0A0A0"]
        for i in range(3):
            # manage icon
            icon = ''
            if i == 2:
                icon =  'check'
                letter_status[letter_number] = i
            # create button and append to button_children
            button_children.append(
                widgets.Button(style={"button_color":color_index[i]},icon=icon)
            )
            # create button observable callback for this button
            bo = create_on_letter_button_clicked(
                letter_number,i
            )
            button_children[i].on_click(bo)

        return button_children

    def make_button_groups():
        but_array = []
        for i in range(5):
            bg = make_button_group(i)
            dropdowns.append(widgets.HBox(bg))
            button_group_array.append(bg)


    make_button_groups()

    wd_box = wordl()

    def on_add_word_button_clicked(change):
        print('-----------')
        word = ''.join(
            [
                tbox.value
                for tbox in tboxes
            ]
        ).lower()
        nums = [
            letter_status[i]+1
            for i in range(5)
        ]

        print(word,nums)
        wd_box.add_word(word,nums)
        reset_word_display()

    button_add_word = widgets.Button(
        description='add_word',
        layout=widgets.Layout(width='auto', height='auto')
    )
    button_add_word.on_click(on_add_word_button_clicked)


    def on_try_it_button_clicked(change):
        words = wd_box.try_it()
        filter_words(words)
    #     display(df_ugf[df_ugf.word.isin(words)].sort_values('count',ascending=False))

    button_tryit = widgets.Button(
        description='try_it',
        layout=widgets.Layout(width='auto', height='auto')
    )
    button_tryit.on_click(on_try_it_button_clicked)

    data_entry_text = widgets.Text()
    gbox0 = widgets.GridBox(
        children=[data_entry_text],
        layout=widgets.Layout(
            display='grid',
            width=f'{perc}%',
            height='auto',
            grid_template_rows='1fr',
            grid_template_columns='1fr'
        )
    )
    def gbox_observer(text_box_changed):
        if text_box_changed['name']=='value':
            if ('new' in text_box_changed) and (len(text_box_changed['new'])>0):
                for i,t in enumerate(text_box_changed['new']):
                    tboxes[i].value = t
    data_entry_text.observe(gbox_observer)

    gbox1 = widgets.GridBox(
        children=tboxes+dropdowns,
        layout=widgets.Layout(
            display='grid',
            width=f'{perc}%',
            height='auto',
            grid_template_rows='1fr 1fr',
            grid_template_columns=' '.join(['auto' for _ in range(len(tboxes))])
        )
    )

    def tb_observer(text_box_changed):
        if text_box_changed['name']=='value':
            if ('new' in text_box_changed) and (len(text_box_changed['new'])>0):
                text_box_changed['owner'].value = text_box_changed['new'][-1].upper()

    for tbox in tboxes:
        tbox.add_class('mytext')
        tbox.observe(tb_observer)

    gbox2 = widgets.HBox(
        children=[button_add_word,button_tryit],
        layout=widgets.Layout(
            display='grid',
            width=f'{perc}%',
            height='auto',
            grid_template_rows='1fr',
            grid_template_columns=' '.join(['auto' for _ in range(2)])
        )
    )

    def reset_word_display():
        for i in range(5):
            tboxes[i].value = ''
            letter_status[i] = 2
            for j in range(2):
                button_group_array[i][j].icon='uncheck'
            button_group_array[i][2].icon='check'
        data_entry_text.value=''
        


    def display_df(df, gap=50, justify='center'):
        html= f"""
        <div style="display:flex; gap:{gap}px; justify-content:{justify};">
            {df._repr_html_()}
        </div>
        """
        return html
    
    def filter_words(words):
        with results_output:
            results_output.clear_output()
            df_new = df_ugf[df_ugf.word.isin(words)].sort_values('count',ascending=False).copy()
            count_sum = df_new['count'].sum()
            df_new['probability'] = df_new['count']/count_sum
            df_new.index = range(1,len(df_new)+1)
#             display(df_new)
            hh = display_df(df_new)
            display_html(hh, raw=True)        



    gbox3 = widgets.VBox([gbox0,gbox1,gbox2],width=f'{perc}%')
    
    hbox_layout = widgets.Layout(
        display='grid',
        width=f'{perc}%',
        height='auto',
        grid_template_rows='1fr',
        grid_template_columns='1fr 1fr',
    )

    display(
        widgets.HBox(
            [
                gbox3,
                results_output
            ],
            layout=hbox_layout
        )
    )

In [12]:
display(widgets.HTML('''<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"> '''))
run_it()
results_output.clear_output()
# results_output

HTML(value='<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesom…

HBox(children=(VBox(children=(GridBox(children=(Text(value=''),), layout=Layout(display='grid', grid_template_…

-----------
slate [3, 3, 3, 3, 1]

In [9]:
wdl = wordl()
wdl.add_word('slate',[3,3,3,3,3])
wdl.add_word('minor',[3,3,2,2,3])
wdl.add_word('goony',[3,2,1,2,3])
wdl.try_it()

['knock', 'known']

In [10]:
wdl = wordl()
wdl.add_word('slate',[3,2,2,3,3])
wdl.add_word('minor',[3,1,3,3,2])
wdl.try_it()

['viral', 'rival']

In [11]:
wdl = wordl()
wdl.add_word('slate',[3,3,3,3,3])
wdl.add_word('minor',[3,3,3,2,2])
r = wdl.try_it()

In [46]:
import string
sss = string.ascii_lowercase
df_conconants = pd.DataFrame([
    [l,df_ww[df_ww.word.str.contains(l)].count().values[0]]
    for l in sss
    if l not in ['a','e','i','o','u']
],columns=['letter','num_times']).sort_values('num_times',ascending=False)

df_vowels = pd.DataFrame([
    [l,df_ww[df_ww.word.str.contains(l)].count().values[0]]
    for l in sss
    if l  in ['a','e','i','o','u']
],columns=['letter','num_times']).sort_values('num_times',ascending=False)

In [47]:
df_ww[df_ww.word.str.contains('a')].count().values[0]

906

In [48]:
df_vowels

  letter  num_times
1      e       1053
0      a        906
3      o        672
2      i        646
4      u        456

In [49]:
df_conconants

   letter  num_times
13      r        835
15      t        667
8       l        645
14      s        617
10      n        548
1       c        446
19      y        416
5       h        377
2       d        370
11      p        345
4       g        299
9       m        298
0       b        266
3       f        206
7       k        202
17      w        193
16      v        148
18      x         37
20      z         35
12      q         29
6       j         27

In [69]:
def part_of(word,letters='sate'):
    return all([l in word for l in letters])

df_wwpo = df_ww[df_ww.word.apply(part_of)]
df_wwpo = df_wwpo.merge(df_ugf,on='word').sort_values('count',ascending=False)
df_wwpo['perc'] = df_wwpo['count'] / df_wwpo['count'].sum()
df_wwpo.head(20)

     word      count      perc
15  state  453104133  0.583505
6   least  111229798  0.143241
11  stage   52518330  0.067633
24  waste   41089558  0.052915
0   asset   18178753  0.023410
22  taste   17311343  0.022293
2   beast   14787561  0.019043
20  steam   11141309  0.014348
7   paste    8913055  0.011478
19  steal    6257493  0.008058
25  yeast    6083904  0.007835
12  stake    5061965  0.006519
9   skate    4932092  0.006352
21  sweat    4551615  0.005862
18  steak    4413680  0.005684
4   feast    4166016  0.005365
10  slate    3813904  0.004912
23  tease    2019275  0.002600
14  stare    1925618  0.002480
3   caste    1166877  0.001503

In [68]:
df_first_letters = pd.DataFrame([
    [l,df_ww[df_ww.word.str.slice(0,1)==l].count().values[0]]
    for l in sss
    if l  in string.ascii_lowercase
],columns=['letter','num_times']).sort_values('num_times',ascending=False)
df_first_letters

   letter  num_times
18      s        365
2       c        198
1       b        173
19      t        149
15      p        141
0       a        140
5       f        135
6       g        115
3       d        111
12      m        107
17      r        105
11      l         87
22      w         82
4       e         72
7       h         69
21      v         43
14      o         41
13      n         37
8       i         34
20      u         33
16      q         23
10      k         20
9       j         20
24      y          6
25      z          3
23      x          0

In [67]:
df_last_letters = pd.DataFrame([
    [l,df_ww[df_ww.word.str.slice(4,5)==l].count().values[0]]
    for l in sss
    if l  in string.ascii_lowercase
],columns=['letter','num_times']).sort_values('num_times',ascending=False)
df_last_letters

   letter  num_times
4       e        422
24      y        364
19      t        253
17      r        212
11      l        155
7       h        137
13      n        130
3       d        118
10      k        113
0       a         63
14      o         58
15      p         56
12      m         42
6       g         41
18      s         36
2       c         31
5       f         26
22      w         17
8       i         11
1       b         11
23      x          8
25      z          4
20      u          1
9       j          0
16      q          0
21      v          0

In [76]:
combos = [''.join(v) for v in list(itertools.permutations(string.ascii_lowercase,2))]
pos = [0,2]
df_common_positions = pd.DataFrame([
    [l,df_ww[df_ww.word.str.slice(pos[0],pos[1])==l].count().values[0]]
    for l in combos
],columns=['combo','num_times']).sort_values('num_times',ascending=False)
df_common_positions

    combo  num_times
468    st         65
457    sh         52
465    sp         45
66     cr         45
56     ch         40
..    ...        ...
305    mf          0
70     cv          0
303    md          0
302    mc          0
649    zy          0

[650 rows x 2 columns]

In [73]:
import itertools
[''.join(v) for v in list(itertools.permutations(string.ascii_lowercase,2))]

['ab',
 'ac',
 'ad',
 'ae',
 'af',
 'ag',
 'ah',
 'ai',
 'aj',
 'ak',
 'al',
 'am',
 'an',
 'ao',
 'ap',
 'aq',
 'ar',
 'as',
 'at',
 'au',
 'av',
 'aw',
 'ax',
 'ay',
 'az',
 'ba',
 'bc',
 'bd',
 'be',
 'bf',
 'bg',
 'bh',
 'bi',
 'bj',
 'bk',
 'bl',
 'bm',
 'bn',
 'bo',
 'bp',
 'bq',
 'br',
 'bs',
 'bt',
 'bu',
 'bv',
 'bw',
 'bx',
 'by',
 'bz',
 'ca',
 'cb',
 'cd',
 'ce',
 'cf',
 'cg',
 'ch',
 'ci',
 'cj',
 'ck',
 'cl',
 'cm',
 'cn',
 'co',
 'cp',
 'cq',
 'cr',
 'cs',
 'ct',
 'cu',
 'cv',
 'cw',
 'cx',
 'cy',
 'cz',
 'da',
 'db',
 'dc',
 'de',
 'df',
 'dg',
 'dh',
 'di',
 'dj',
 'dk',
 'dl',
 'dm',
 'dn',
 'do',
 'dp',
 'dq',
 'dr',
 'ds',
 'dt',
 'du',
 'dv',
 'dw',
 'dx',
 'dy',
 'dz',
 'ea',
 'eb',
 'ec',
 'ed',
 'ef',
 'eg',
 'eh',
 'ei',
 'ej',
 'ek',
 'el',
 'em',
 'en',
 'eo',
 'ep',
 'eq',
 'er',
 'es',
 'et',
 'eu',
 'ev',
 'ew',
 'ex',
 'ey',
 'ez',
 'fa',
 'fb',
 'fc',
 'fd',
 'fe',
 'fg',
 'fh',
 'fi',
 'fj',
 'fk',
 'fl',
 'fm',
 'fn',
 'fo',
 'fp',
 'fq',
 'fr',
 'fs',
 'ft',
 'fu',
 'fv',
 'fw',
 'fx',
 'fy',
 'fz',
 'ga',
 'gb',
 'gc',
 'gd',
 'ge',
 'gf',
 'gh',
 'gi',
 'gj',
 'gk',
 'gl',
 'gm',
 'gn',
 'go',
 'gp',
 'gq',
 'gr',
 'gs',
 'gt',
 'gu',
 'gv',
 'gw',
 'gx',
 'gy',
 'gz',
 'ha',
 'hb',
 'hc',
 'hd',
 'he',
 'hf',
 'hg',
 'hi',
 'hj',
 'hk',
 'hl',
 'hm',
 'hn',
 'ho',
 'hp',
 'hq',
 'hr',
 'hs',
 'ht',
 'hu',
 'hv',
 'hw',
 'hx',
 'hy',
 'hz',
 'ia',
 'ib',
 'ic',
 'id',
 'ie',
 'if',
 'ig',
 'ih',
 'ij',
 'ik',
 'il',
 'im',
 'in',
 'io',
 'ip',
 'iq',
 'ir',
 'is',
 'it',
 'iu',
 'iv',
 'iw',
 'ix',
 'iy',
 'iz',
 'ja',
 'jb',
 'jc',
 'jd',
 'je',
 'jf',
 'jg',
 'jh',
 'ji',
 'jk',
 'jl',
 'jm',
 'jn',
 'jo',
 'jp',
 'jq',
 'jr',
 'js',
 'jt',
 'ju',
 'jv',
 'jw',
 'jx',
 'jy',
 'jz',
 'ka',
 'kb',
 'kc',
 'kd',
 'ke',
 'kf',
 'kg',
 'kh',
 'ki',
 'kj',
 'kl',
 'km',
 'kn',
 'ko',
 'kp',
 'kq',
 'kr',
 'ks',
 'kt',
 'ku',
 'kv',
 'kw',
 'kx',
 'ky',
 'kz',
 'la',
 'lb',
 'lc',
 'ld',
 'le',
 'lf',
 'lg',
 'lh',
 'li',
 'lj',
 'lk',
 'lm',
 'ln',
 'lo',
 'lp',
 'lq',
 'lr',
 'ls',
 'lt',
 'lu',
 'lv',
 'lw',
 'lx',
 'ly',
 'lz',
 'ma',
 'mb',
 'mc',
 'md',
 'me',
 'mf',
 'mg',
 'mh',
 'mi',
 'mj',
 'mk',
 'ml',
 'mn',
 'mo',
 'mp',
 'mq',
 'mr',
 'ms',
 'mt',
 'mu',
 'mv',
 'mw',
 'mx',
 'my',
 'mz',
 'na',
 'nb',
 'nc',
 'nd',
 'ne',
 'nf',
 'ng',
 'nh',
 'ni',
 'nj',
 'nk',
 'nl',
 'nm',
 'no',
 'np',
 'nq',
 'nr',
 'ns',
 'nt',
 'nu',
 'nv',
 'nw',
 'nx',
 'ny',
 'nz',
 'oa',
 'ob',
 'oc',
 'od',
 'oe',
 'of',
 'og',
 'oh',
 'oi',
 'oj',
 'ok',
 'ol',
 'om',
 'on',
 'op',
 'oq',
 'or',
 'os',
 'ot',
 'ou',
 'ov',
 'ow',
 'ox',
 'oy',
 'oz',
 'pa',
 'pb',
 'pc',
 'pd',
 'pe',
 'pf',
 'pg',
 'ph',
 'pi',
 'pj',
 'pk',
 'pl',
 'pm',
 'pn',
 'po',
 'pq',
 'pr',
 'ps',
 'pt',
 'pu',
 'pv',
 'pw',
 'px',
 'py',
 'pz',
 'qa',
 'qb',
 'qc',
 'qd',
 'qe',
 'qf',
 'qg',
 'qh',
 'qi',
 'qj',
 'qk',
 'ql',
 'qm',
 'qn',
 'qo',
 'qp',
 'qr',
 'qs',
 'qt',
 'qu',
 'qv',
 'qw',
 'qx',
 'qy',
 'qz',
 'ra',
 'rb',
 'rc',
 'rd',
 're',
 'rf',
 'rg',
 'rh',
 'ri',
 'rj',
 'rk',
 'rl',
 'rm',
 'rn',
 'ro',
 'rp',
 'rq',
 'rs',
 'rt',
 'ru',
 'rv',
 'rw',
 'rx',
 'ry',
 'rz',
 'sa',
 'sb',
 'sc',
 'sd',
 'se',
 'sf',
 'sg',
 'sh',
 'si',
 'sj',
 'sk',
 'sl',
 'sm',
 'sn',
 'so',
 'sp',
 'sq',
 'sr',
 'st',
 'su',
 'sv',
 'sw',
 'sx',
 'sy',
 'sz',
 'ta',
 'tb',
 'tc',
 'td',
 'te',
 'tf',
 'tg',
 'th',
 'ti',
 'tj',
 'tk',
 'tl',
 'tm',
 'tn',
 'to',
 'tp',
 'tq',
 'tr',
 'ts',
 'tu',
 'tv',
 'tw',
 'tx',
 'ty',
 'tz',
 'ua',
 'ub',
 'uc',
 'ud',
 'ue',
 'uf',
 'ug',
 'uh',
 'ui',
 'uj',
 'uk',
 'ul',
 'um',
 'un',
 'uo',
 'up',
 'uq',
 'ur',
 'us',
 'ut',
 'uv',
 'uw',
 'ux',
 'uy',
 'uz',
 'va',
 'vb',
 'vc',
 'vd',
 've',
 'vf',
 'vg',
 'vh',
 'vi',
 'vj',
 'vk',
 'vl',
 'vm',
 'vn',
 'vo',
 'vp',
 'vq',
 'vr',
 'vs',
 'vt',
 'vu',
 'vw',
 'vx',
 'vy',
 'vz',
 'wa',
 'wb',
 'wc',
 'wd',
 'we',
 'wf',
 'wg',
 'wh',
 'wi',
 'wj',
 'wk',
 'wl',
 'wm',
 'wn',
 'wo',
 'wp',
 'wq',
 'wr',
 'ws',
 'wt',
 'wu',
 'wv',
 'wx',
 'wy',
 'wz',
 'xa',
 'xb',
 'xc',
 'xd',
 'xe',
 'xf',
 'xg',
 'xh',
 'xi',
 'xj',
 'xk',
 'xl',
 'xm',
 'xn',
 'xo',
 'xp',
 'xq',
 'xr',
 'xs',
 'xt',
 'xu',
 'xv',
 'xw',
 'xy',
 'xz',
 'ya',
 'yb',
 'yc',
 'yd',
 'ye',
 'yf',
 'yg',
 'yh',
 'yi',
 'yj',
 'yk',
 'yl',
 'ym',
 'yn',
 'yo',
 'yp',
 'yq',
 'yr',
 'ys',
 'yt',
 'yu',
 'yv',
 'yw',
 'yx',
 'yz',
 'za',
 'zb',
 'zc',
 'zd',
 'ze',
 'zf',
 'zg',
 'zh',
 'zi',
 'zj',
 'zk',
 'zl',
 'zm',
 'zn',
 'zo',
 'zp',
 'zq',
 'zr',
 'zs',
 'zt',
 'zu',
 'zv',
 'zw',
 'zx',
 'zy']